
spring:
      datasource:
        url: jdbc:mysql://127.0.0.1:3306/testDB
        username: zorba
        password: zorba
        driver-class-name: com.mysql.jdbc.Driver

        jpa:
          hibernate:
            naming:
              physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

server:
    port: 8081








